In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

%matplotlib inline

In [3]:
data = pd.read_csv("6-bank_customers.csv")

In [4]:
data

age  job_satisfaction   balance  duration_last_call  \
0   -0.377957          1.043895  1.043494           -0.101838   
1   -0.325259          1.276263 -0.686123           -2.463205   
2    0.739019         -0.600903 -0.177294            1.335714   
3    0.474312         -1.103002  1.189936           -0.800186   
4    0.927365          1.114796  0.080284            1.261064   
..        ...               ...       ...                 ...   
995  1.538272          0.171629  0.075371           -0.957658   
996 -0.060266          0.095018 -0.271685            1.830560   
997  0.675563         -0.538420 -1.299500            0.747835   
998  2.629710         -2.452899 -1.359785            1.592065   
999 -1.791491         -0.121908  0.535153           -0.588085   

     num_contacts_last_month  has_housing_loan  has_personal_loan  \
0                  -1.617442          0.402713           0.913601   
1                  -0.489426         -0.240715          -1.469496   
2                  -0.817332         -0.790047           1.457365   
3                   0.912377         -0.406451          -1.130950   
4                   0.761179          0.921563           0.440832   
..                       ...               ...                ...   
995                -1.066219          1.158096          -0.036964   
996                 0.219445         -0.341269           1.180088   
997                 1.733898         -0.268044          -0.520953   
998                 0.854157          1.618828           0.621701   
999                -1.929461         -0.659900           0.754921   

     communication_type  days_since_last_contact  campaign_response_score  \
0             -0.067192                 0.175471                -1.049646   
1              1.006633                -0.833692                 0.957744   
2             -0.218981                 0.878643                -1.257740   
3              1.985111                 1.379029                 1.041768   
4              0.184645                -1.567739                -0.142107   
..                  ...                      ...                      ...   
995            0.123689                 0.927871                -0.225003   
996           -0.216876                -1.752938                -0.810152   
997            2.043336                 0.947388                 0.790354   
998            0.378898                -1.971894                -0.252250   
999           -1.941357                 0.589002                -1.007482   

     subscribed  
0             0  
1             0  
2             0  
3             1  
4             1  
..          ...  
995           0  
996           1  
997           1  
998           1  
999           0  

[1000 rows x 11 columns]

In [5]:
data.columns

Index(['age', 'job_satisfaction', 'balance', 'duration_last_call',
       'num_contacts_last_month', 'has_housing_loan', 'has_personal_loan',
       'communication_type', 'days_since_last_contact',
       'campaign_response_score', 'subscribed'],
      dtype='object')

In [6]:
data.head()

age  job_satisfaction   balance  duration_last_call  \
0 -0.377957          1.043895  1.043494           -0.101838   
1 -0.325259          1.276263 -0.686123           -2.463205   
2  0.739019         -0.600903 -0.177294            1.335714   
3  0.474312         -1.103002  1.189936           -0.800186   
4  0.927365          1.114796  0.080284            1.261064   

   num_contacts_last_month  has_housing_loan  has_personal_loan  \
0                -1.617442          0.402713           0.913601   
1                -0.489426         -0.240715          -1.469496   
2                -0.817332         -0.790047           1.457365   
3                 0.912377         -0.406451          -1.130950   
4                 0.761179          0.921563           0.440832   

   communication_type  days_since_last_contact  campaign_response_score  \
0           -0.067192                 0.175471                -1.049646   
1            1.006633                -0.833692                 0.957744   
2           -0.218981                 0.878643                -1.257740   
3            1.985111                 1.379029                 1.041768   
4            0.184645                -1.567739                -0.142107   

   subscribed  
0           0  
1           0  
2           0  
3           1  
4           1

In [7]:
data.describe()

age  job_satisfaction      balance  duration_last_call  \
count  1000.000000       1000.000000  1000.000000         1000.000000   
mean     -0.015084          0.031559     0.045069           -0.020771   
std       1.021848          1.004281     1.006910            1.392738   
min      -3.718638         -3.116027    -3.534257           -4.999018   
25%      -0.685005         -0.657545    -0.647051           -1.057938   
50%      -0.030546          0.045869     0.040586            0.204506   
75%       0.662124          0.701601     0.731615            1.061181   
max       2.765266          2.658705     3.357941            3.477210   

       num_contacts_last_month  has_housing_loan  has_personal_loan  \
count              1000.000000       1000.000000        1000.000000   
mean                  0.016769         -0.042135          -0.025139   
std                   1.268761          1.029279           1.267490   
min                  -2.587178         -3.250031          -4.932878   
25%                  -0.981320         -0.722970          -0.855392   
50%                  -0.317137         -0.022343           0.148199   
75%                   1.017388          0.596557           1.020255   
max                   3.954873          3.206344           2.343380   

       communication_type  days_since_last_contact  campaign_response_score  \
count         1000.000000              1000.000000              1000.000000   
mean             0.058969                -0.015637                 0.022327   
std              0.992629                 1.000664                 1.135131   
min             -3.187779                -2.819987                -2.071129   
25%             -0.598669                -0.693330                -1.050201   
50%              0.052208                 0.018807                -0.037530   
75%              0.722446                 0.641338                 0.760782   
max              3.600187                 3.477044                 4.124285   

        subscribed  
count  1000.000000  
mean      0.503000  
std       0.500241  
min       0.000000  
25%       0.000000  
50%       1.000000  
75%       1.000000  
max       1.000000

In [8]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 11 columns):
 #   Column                   Non-Null Count  Dtype  
---  ------                   --------------  -----  
 0   age                      1000 non-null   float64
 1   job_satisfaction         1000 non-null   float64
 2   balance                  1000 non-null   float64
 3   duration_last_call       1000 non-null   float64
 4   num_contacts_last_month  1000 non-null   float64
 5   has_housing_loan         1000 non-null   float64
 6   has_personal_loan        1000 non-null   float64
 7   communication_type       1000 non-null   float64
 8   days_since_last_contact  1000 non-null   float64
 9   campaign_response_score  1000 non-null   float64
 10  subscribed               1000 non-null   int64  
dtypes: float64(10), int64(1)
memory usage: 86.1 KB


In [11]:
X = data.drop("subscribed", axis=1)
y = data["subscribed"]

In [12]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=15)

In [13]:
from sklearn.linear_model import LogisticRegression

In [16]:
logistic = LogisticRegression()

logistic.fit(X_train, y_train)
y_pred = logistic.predict(X_test)

In [17]:
y_pred

array([0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1,
       1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0,
       1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1,
       0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0,
       1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0,
       1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0,
       0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0,
       1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0,
       1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1,
       0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0,
       0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0,
       1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1])

In [20]:
from sklearn.metrics import confusion_matrix, classification_report, accuracy_score

In [23]:
#score = accuracy_score(y_pred, y_test) #can also be used this way on small data sets
score = accuracy_score(y_test, y_pred)

print("Score: ", score)

print(classification_report(y_pred, y_test))

print("Confusion Matrix: \n",confusion_matrix(y_pred, y_test))


Score:  0.92
              precision    recall  f1-score   support

           0       0.92      0.91      0.92       147
           1       0.92      0.93      0.92       153

    accuracy                           0.92       300
   macro avg       0.92      0.92      0.92       300
weighted avg       0.92      0.92      0.92       300

Confusion Matrix: 
 [[134  13]
 [ 11 142]]


In [24]:
# hyperparameter tuning

In [25]:
model = LogisticRegression()

In [26]:
#https://scikit-learn.org/stable/modules/generated/sklearn.linear_model.LogisticRegression.html

penalty = ["l1","l2","elasticnet"]
c_values = [100, 10, 1, 0.1, 0.01]
solver = ["newton-cg", "lbfgs", "liblinear", "sag", "saga", "newton-cholesky"]

In [27]:
params = dict(penalty=penalty, C=c_values, solver=solver)

In [28]:
params

{'penalty': ['l1', 'l2', 'elasticnet'],
 'C': [100, 10, 1, 0.1, 0.01],
 'solver': ['newton-cg',
  'lbfgs',
  'liblinear',
  'sag',
  'saga',
  'newton-cholesky']}

In [29]:
# grid search cv

In [30]:
from sklearn.model_selection import GridSearchCV, StratifiedKFold

In [31]:
cv = StratifiedKFold() # n_splits=d default value

In [34]:
# https://scikit-learn.org/stable/modules/generated/sklearn.model_selection.GridSearchCV.html
# https://scikit-learn.org/stable/modules/model_evaluation.html#scoring-api-overview !"scoring"

# n_jobs=-1, Use as much space as you have on your CPU

grid = GridSearchCV(estimator=model, param_grid=params, cv=cv, scoring="accuracy", n_jobs=-1)

In [35]:
grid

GridSearchCV(cv=StratifiedKFold(n_splits=5, random_state=None, shuffle=False),
             estimator=LogisticRegression(), n_jobs=-1,
             param_grid={'C': [100, 10, 1, 0.1, 0.01],
                         'penalty': ['l1', 'l2', 'elasticnet'],
                         'solver': ['newton-cg', 'lbfgs', 'liblinear', 'sag',
                                    'saga', 'newton-cholesky']},
             scoring='accuracy')

In [36]:
grid.fit(X_train, y_train)

D:\PycharmProjects\MachineLearningNotes\.venv\Lib\site-packages\sklearn\model_selection\_validation.py:516: FitFailedWarning: 
250 fits failed out of a total of 450.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
25 fits failed with the following error:
Traceback (most recent call last):
  File "D:\PycharmProjects\MachineLearningNotes\.venv\Lib\site-packages\sklearn\model_selection\_validation.py", line 859, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
    ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PycharmProjects\MachineLearningNotes\.venv\Lib\site-packages\sklearn\base.py", line 1365, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "D:\PycharmProjects\MachineLearningNotes\.venv\

GridSearchCV(cv=StratifiedKFold(n_splits=5, random_state=None, shuffle=False),
             estimator=LogisticRegression(), n_jobs=-1,
             param_grid={'C': [100, 10, 1, 0.1, 0.01],
                         'penalty': ['l1', 'l2', 'elasticnet'],
                         'solver': ['newton-cg', 'lbfgs', 'liblinear', 'sag',
                                    'saga', 'newton-cholesky']},
             scoring='accuracy')

In [37]:
grid.best_params_

{'C': 0.1, 'penalty': 'l2', 'solver': 'liblinear'}

In [38]:
grid.best_score_

np.float64(0.9228571428571429)

In [39]:
y_pred = grid.predict(X_test)

In [41]:
score = accuracy_score(y_test, y_pred)

print("Score: ", score)

print(classification_report(y_pred, y_test))

print("Confusion Matrix: \n",confusion_matrix(y_pred, y_test))

Score:  0.9233333333333333
              precision    recall  f1-score   support

           0       0.94      0.90      0.92       152
           1       0.90      0.95      0.92       148

    accuracy                           0.92       300
   macro avg       0.92      0.92      0.92       300
weighted avg       0.92      0.92      0.92       300

Confusion Matrix: 
 [[137  15]
 [  8 140]]


In [42]:
# randon search cv

In [59]:
from sklearn.model_selection import RandomizedSearchCV

In [60]:
model = LogisticRegression()

In [61]:
# https://scikit-learn.org/stable/modules/generated/sklearn.model_selection.RandomizedSearchCV.html

randomcv = RandomizedSearchCV(estimator=model, param_distributions=params, cv=5, n_iter=10, scoring="accuracy")

In [62]:
randomcv.fit(X_train, y_train)

D:\PycharmProjects\MachineLearningNotes\.venv\Lib\site-packages\sklearn\model_selection\_validation.py:516: FitFailedWarning: 
35 fits failed out of a total of 50.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
5 fits failed with the following error:
Traceback (most recent call last):
  File "D:\PycharmProjects\MachineLearningNotes\.venv\Lib\site-packages\sklearn\model_selection\_validation.py", line 859, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
    ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PycharmProjects\MachineLearningNotes\.venv\Lib\site-packages\sklearn\base.py", line 1365, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "D:\PycharmProjects\MachineLearningNotes\.venv\Lib

RandomizedSearchCV(cv=5, estimator=LogisticRegression(),
                   param_distributions={'C': [100, 10, 1, 0.1, 0.01],
                                        'penalty': ['l1', 'l2', 'elasticnet'],
                                        'solver': ['newton-cg', 'lbfgs',
                                                   'liblinear', 'sag', 'saga',
                                                   'newton-cholesky']},
                   scoring='accuracy')

In [63]:
randomcv.best_params_

{'solver': 'saga', 'penalty': 'l2', 'C': 0.1}

In [64]:
randomcv.best_score_

np.float64(0.9214285714285715)

In [65]:
y_pred = randomcv.predict(X_test)

In [69]:
score = accuracy_score(y_test, y_pred)

print("Score: ", score)

print(classification_report(y_pred, y_test))

print("Confusion Matrix: \n",confusion_matrix(y_pred, y_test))

Score:  0.92
              precision    recall  f1-score   support

           0       0.94      0.90      0.92       151
           1       0.90      0.94      0.92       149

    accuracy                           0.92       300
   macro avg       0.92      0.92      0.92       300
weighted avg       0.92      0.92      0.92       300

Confusion Matrix: 
 [[136  15]
 [  9 140]]
